# Generated by Django 5.0.3 on 2026-05-24 20:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_key', models.CharField(max_length=255, unique=True)),
                ('activity_type', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR_RENTAL', 'Car rental'), ('RAIL', 'Rail')], max_length=30)),
                ('scope', models.PositiveSmallIntegerField()),
                ('scope3_category', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=18)),
                ('factor_unit', models.CharField(max_length=80)),
                ('geography', models.CharField(blank=True, max_length=120)),
                ('source_name', models.CharField(max_length=255)),
                ('effective_year', models.PositiveSmallIntegerField(default=2024)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['activity_type', 'scope'], name='emissions_e_activit_6c06eb_idx'), models.Index(fields=['is_default'], name='emissions_e_is_defa_08de5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_summary', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=20)),
                ('activity_type', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('CAR_RENTAL', 'Car rental'), ('RAIL', 'Rail')], max_length=30)),
                ('scope', models.PositiveSmallIntegerField()),
                ('scope3_category', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_start_date', models.DateField(blank=True, null=True)),
                ('activity_end_date', models.DateField(blank=True, null=True)),
                ('raw_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=40)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=40)),
                ('conversion_factor_used', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=80)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=20)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('needs_info', 'Needs info'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending_review', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_activities', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_activities', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='emissions.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
            options={
                'verbose_name_plural': 'Emission activities',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('unlocked_by_admin', 'Unlocked by admin')], max_length=30)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='emissions.emissionactivity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawSourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('source_record_key', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField()),
                ('parse_status', models.CharField(choices=[('parsed', 'Parsed'), ('warning', 'Warning'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.ingestionbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
            ],
        ),
        migrations.AddField(
            model_name='emissionactivity',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='emissions.rawsourcerecord'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['organization', 'source_type'], name='emissions_i_organiz_b3a971_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['file_hash'], name='emissions_i_file_ha_0e2ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'action'], name='emissions_a_organiz_e3a5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['activity', 'created_at'], name='emissions_a_activit_73f42e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsourcerecord',
            index=models.Index(fields=['organization', 'source_record_key'], name='emissions_r_organiz_177355_idx'),
        ),
        migrations.AddIndex(
            model_name='rawsourcerecord',
            index=models.Index(fields=['batch', 'parse_status'], name='emissions_r_batch_i_0e51f4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionactivity',
            index=models.Index(fields=['organization', 'source_type'], name='emissions_e_organiz_405c49_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionactivity',
            index=models.Index(fields=['scope', 'status'], name='emissions_e_scope_fab8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionactivity',
            index=models.Index(fields=['activity_type', 'confidence'], name='emissions_e_activit_5691e6_idx'),
        ),
    ]
